spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
      open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      platform: h2
      scripts: classpath:schema.sql,classpath:data.sql

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
    root: INFO  # Set the global logging level to INFO
    tacos: DEBUG  # Assuming 'tacos' is your base package, set logging for your application code to DEBUG
