spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
      open-in-view: false
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      platform: h2
      scripts: classpath:schema.sql,classpath:data.sql